# recipe.yml - Beispiel für ein Drupal Recipe
apiVersion: 1
kind: Recipe
metadata:
  name: stadtportal
  description: "Ein Drupal-Recipe für ein Stadtportal"
  version: 1.0.0

dependencies:
  - drupal/core-recommended
  - drupal/core-composer-scaffold
  - drupal/core-project-message
  - drupal/admin_toolbar
  - drupal/pathauto
  - drupal/metatag

modules:
  enable:
    - admin_toolbar
    - pathauto
    - metatag

config:
  import:
    - config/install

themes:
  default: claro

# Optional: Weitere Einstellungen, z.B. Benutzerrollen, Berechtigungen, etc.